# GRUB2 EFI bootloader for installed Neom systems
---
efiBootLoader: "systemd-boot"

kernelSearchPath: "/usr/lib/modules"
kernelPattern: "^vmlinuz.*"

kernelParams: [ "quiet" ]

grubInstall: "grub2-install"
grubMkconfig: "grub2-mkconfig"
grubCfg: "/boot/grub2/grub.cfg"
grubProbe: "grub2-probe"
efiBootMgr: "efibootmgr"

installEFIFallback: true
