# EFI + root + swap defaults for Neo
---
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 512MiB
    minimumSize: 512MiB
    label: "EFI"

userSwapChoices:
    - none
    - small
    - suspend

defaultFileSystemType: "btrfs"

availableFileSystemTypes:
    - "ext4"
    - "btrfs"
    - "xfs"

requirePartitionTableType: "gpt"
