# Enable core services on installed Neo systems
---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "plasmalogin.service"
    action: "enable"
    mandatory: true
  - name: "bluetooth.service"
    action: "enable"
  - name: "gamemoded.service"
    action: "enable"
  - name: "graphical.target"
    action: "enable"
