# First user + admin for Neom installation
---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - name: wheel
      must_exist: false
      system: true
    - name: video
      must_exist: false
      system: true
    - name: audio
      must_exist: false
      system: true
    - name: render
      must_exist: false
      system: true

sudoersGroup: wheel

setRootPassword: false
doReusePassword: false

writeHostnameFile: true
hostnameTemplate: "neo"
